/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.liferay.test;

import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

import jodd.http.HttpProgressListener;
import jodd.http.HttpRequest;
import jodd.http.HttpResponse;
import jodd.io.FileUtil;

public class JournalArticleCreator7010 {
	static File imageFile1;
	static File imageFile2;
	static File imageFile3;
	static File imageFile4;
	static HttpRequest httpRequest;
	static int requestSize;
	static String groupIdAsString;
	static long groupId;
	static String ddmStructureKey;
	static String ddmTemplateKey;
	static String imageFileNameString1;
	static String imageFileNameString2;
	static String imageFileNameString3;
	static String imageFileNameString4;
	static String imageFilePathString1;
	static String imageFilePathString2;
	static String imageFilePathString3;
	static String imageFilePathString4;
	static long folderId;
	static long classNameId;
	static long classPK;
	static long articleId;
	static boolean autoArticleId;
	static String layoutUuid;
	static boolean neverExpire;
	static boolean neverReview;
	static boolean indexable;
	static boolean smallImage;
	static String smallImageURL;
	static String smallFile;
	static String articleURL;
	static String username;
	static String password;

	public static void main(String[] args) throws IOException {
		createJournalArticleWithImage();
	}

	private static void createJournalArticleWithImage() throws IOException {
		// Working on 24 Aug 2019
		// Note: there were no DuplicateFileEntryException errors while testing
		// Note2: In the Portal, the file size is checked here:
		// Control Panel / Configuration / System Settings / Documents and Media
		// / Maximum File Size
		// Note3: The correct syntax for the images Map:
//		{"filename1.ext":[-119, 80, ... ],"filename2.ext":[-119, 80, ... ]}

//		username= JOptionPane.showInputDialog("Please enter the username:");
		username="test@liferay.com";
		
//		password= JOptionPane.showInputDialog("Please enter the password:");
		password="test";
		
//		groupIdAsString = JOptionPane.showInputDialog("Please enter the groupId:");
		groupIdAsString = "20142";
		groupId = Integer.parseInt(groupIdAsString);

//		ddmStructureKey = JOptionPane.showInputDialog("Please enter the ddmStructureKey:");
		ddmStructureKey = "36680";

//		ddmTemplateKey = JOptionPane.showInputDialog("Please enter the ddmTemplateKey:");
		ddmTemplateKey = "36684";

//		JFileChooser chooser = new JFileChooser();
//		FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");
//		chooser.setFileFilter(filter);
//		chooser.setDialogTitle("Please select the image you would like to upload");
//		int returnVal = chooser.showOpenDialog(null);
//		if (returnVal == JFileChooser.APPROVE_OPTION) {
//			imageFile1 = chooser.getSelectedFile().getAbsoluteFile();
//			System.out.println("You chose to upload this file: " + imageFile1.getName());
//		}
		
		imageFilePathString1="/home/peterpetrekanics/Pictures/test_pictures/1.png";
		imageFilePathString2="/home/peterpetrekanics/Pictures/test_pictures/2.png";
		imageFilePathString3="/home/peterpetrekanics/Pictures/test_pictures/3.png";
		imageFilePathString4="/home/peterpetrekanics/Pictures/test_pictures/4.png";
		
		imageFile1 = new File(imageFilePathString1);
		imageFile2 = new File(imageFilePathString2);
		imageFile3 = new File(imageFilePathString3);
		imageFile4 = new File(imageFilePathString4);

		imageFileNameString1 = imageFile1.getName();
		byte[] bytes1 = FileUtil.readBytes(imageFile1);
		imageFileNameString2 = imageFile2.getName();
		byte[] bytes2 = FileUtil.readBytes(imageFile2);
		imageFileNameString2 = imageFile2.getName();
		byte[] bytes3 = FileUtil.readBytes(imageFile3);
		imageFileNameString3 = imageFile3.getName();
		byte[] bytes4 = FileUtil.readBytes(imageFile4);
		imageFileNameString4 = imageFile4.getName();
		
		String bytesString1 = Arrays.toString(bytes1);
		String bytesString2 = Arrays.toString(bytes2);
		String bytesString3 = Arrays.toString(bytes3);
		String bytesString4 = Arrays.toString(bytes4);
//		String images = "{\"" + imageFileNameString1 + "\":" + bytesString1 + "}";

		String images1 = "\"" + imageFileNameString1 + "\":" + bytesString1 + "";
		String images2 = "\"" + imageFileNameString2 + "\":" + bytesString2 + "";
		String images3 = "\"" + imageFileNameString3 + "\":" + bytesString3 + "";
		String images4 = "\"" + imageFileNameString4 + "\":" + bytesString4 + "";
		String imagesString = "{" + images1 + "," + images2  + "," + images3  + "," + images4 + "}";

		String serviceContext = "{\"addGroupPermissions\":false" + 
				",\"addGuestPermissions\":false" + ", \"scopeGroupId\":\"0\"}";

		String actionUrl = "http://localhost:8080/api/jsonws/journal.journalarticle/add-article";
		
		// As a display date, we use yesterday: otherwise the article will be created with a
		// "scheduled" state, but we want the article to appear on the Portal immediately
		Calendar yesterday = Calendar.getInstance();
		yesterday.add(Calendar.DAY_OF_YEAR, -1);
		Calendar nextWeek = Calendar.getInstance();
		nextWeek.add(Calendar.WEEK_OF_YEAR, 1);
		int displayDateHour = yesterday.get(Calendar.HOUR_OF_DAY);
		int displayDateMinute = yesterday.get(Calendar.MINUTE);
		String timenow = displayDateHour + ":" + displayDateMinute;
		String titleMap = "{\"en_US\":\"Test Article created on " + timenow + "\"}";
		String descriptionMap = "{\"en_US\":\"Description SG2\"}";

		// Important note: the content variable must match the structure's setup
//		String content = "<?xml version=\"1.0\"?><root></root>";
		String content = "<?xml version=\"1.0\"?><root available-locales=\"fr_FR,en_US\" default-locale=\"en_US\"><dynamic-element name=\"text\" type=\"text\" index-type=\"keyword\" instance-id=\"qmcr\"><dynamic-content language-id=\"fr_FR\"><![CDATA[Bonjour, monde!]]></dynamic-content><dynamic-content language-id=\"en_US\"><![CDATA[Hello, world!]]></dynamic-content></dynamic-element></root>";

		folderId = 0;
		classNameId = 0;
		classPK = 0;
		articleId = 0;
		autoArticleId = true;
		layoutUuid = "";
		neverExpire = true;
		neverReview = true;
		indexable = true;
		smallImage = false;
		smallImageURL = "";
		smallFile = "";
		articleURL = "";

		HttpResponse httpResponse = HttpRequest.post(actionUrl).multipart(true) // this is the key, without this line
																				// only the small files can be uploaded
				.form("groupId", groupId, // 20142,
						"folderId", folderId,
						"classNameId", classNameId,
						"classPK", classPK,
						"articleId", articleId,
						"autoArticleId", autoArticleId,
						"titleMap", titleMap,
						"descriptionMap", descriptionMap,
						"content", content,
						"ddmStructureKey", ddmStructureKey, // 31865,
						"ddmTemplateKey", ddmTemplateKey, // 31873,
						"layoutUuid", layoutUuid,
						"displayDateMonth", "" + (yesterday.get(Calendar.MONTH)),
						"displayDateDay", "" + yesterday.get(Calendar.DAY_OF_MONTH),
						"displayDateYear","" + yesterday.get(Calendar.YEAR),
						"displayDateHour", "" + yesterday.get(Calendar.HOUR_OF_DAY),
						"displayDateMinute", "" + yesterday.get(Calendar.MINUTE),
						"expirationDateMonth", "" + (1 + nextWeek.get(Calendar.MONTH)),
						"expirationDateDay", "" + nextWeek.get(Calendar.DAY_OF_MONTH),
						"expirationDateYear", "" + nextWeek.get(Calendar.YEAR),
						"expirationDateHour", "" + nextWeek.get(Calendar.HOUR_OF_DAY),
						"expirationDateMinute", "" + nextWeek.get(Calendar.MINUTE),
						"neverExpire", neverExpire,
						"reviewDateMonth", "" + (1 + nextWeek.get(Calendar.MONTH)),
						"reviewDateDay", "" + nextWeek.get(Calendar.DAY_OF_MONTH),
						"reviewDateYear", "" + nextWeek.get(Calendar.YEAR),
						"reviewDateHour", "" + nextWeek.get(Calendar.HOUR_OF_DAY),
						"reviewDateMinute", "" + nextWeek.get(Calendar.MINUTE),
						"neverReview", neverReview,
						"indexable", indexable,
						"smallImage", smallImage,
						"smallImageURL", smallImageURL,
						"smallFile", smallFile,
						"images", imagesString,
						"articleURL", articleURL,
						"serviceContext", serviceContext

				).monitor(new HttpProgressListener() {
					@Override
					public void transferred(int len) {
						requestSize = size;
						int percentage = (len * 100) / size;
						System.out.println("Uploaded: " + percentage + "%");
					}
				}).basicAuthentication(username, password).send();

		// Note3: during testing the below JOptionPane froze, so we wont be using it:
//		JOptionPane.showMessageDialog(null, httpResponse.toString(), "Response from the Portal: ",
//				JOptionPane.INFORMATION_MESSAGE);
		System.out.println("Response from the Portal: " + httpResponse.toString());
	}
}
