/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.liferay.test;

import org.junit.Test;
import static org.junit.Assert.*;

public class JournalArticleCreator7010Test {
    @Test public void testJournalArticleCreator7010() {
    }
}
